name: Lab 4 CI

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run a one-line script
        run: echo "Hello, GitHub Actions!"
        - name: Break the build
        run: exit 0
